name: Self-Hosted Runner Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Print Runner Name
        run: echo "Runner is ARM"

      - name: Run the Docker container
        run: |
          docker run --rm arm64v8/hello-world
